input_boolean:
  home_mode:
    name: Home Mode
    icon: mdi:home-account
  guest_mode:
    name: Guest Mode
    icon: mdi:account-group
  andre_mode:
    name: Andre Mode
    icon: mdi:account
  vacances:
    name: Vacances
    icon: mdi:beach

input_select:
  house_profile:
    name: House Profile
    options:
      - normal
      - quiet
      - away
    initial: normal
    icon: mdi:tune-variant

timer:
  focus_session:
    name: Focus Session
    duration: "00:25:00"
